### ISSUE TITLE
Failing to find parse module

### ISSUE THREAD

**Issue by dandiodati** [jd/git-pull-request#25]
Getting the following error on a MacOS Sierra (10.12.3). Is python 2.7 supported ?:
Traceback (most recent call last):
  File "/usr/local/bin/git-pull-request", line 7, in <module>
    from git_pull_request import main
  File "/Library/Python/2.7/site-packages/git_pull_request/__init__.py", line 26, in <module>
    from urllib import parse
ImportError: cannot import name parse

**Comment by dandiodati** [comment]
Works with python 3.6 so closing this.
